apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow-extension
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customized-rolebinding-creator-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["get", "create", "list"]
  - apiGroups: ["kubeflow.org"]
    resources: ["profiles"]
    verbs: ["get", "list"]
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeflow-extension-default-rolebinding
roleRef:
  kind: ClusterRole
  name: customized-rolebinding-creator-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: default
    namespace: kubeflow-extension
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-all-sa_ns-kubeflow-extension
  namespace: kubeflow-extension
roleRef:
  kind: ClusterRole
  name: psp:vmware-system-privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolebinding-creator
  namespace: kubeflow-extension
  labels:
    app: rolebinding-creator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolebinding-creator
  template:
    metadata:
      labels:
        app: rolebinding-creator
    spec:
      containers:
        - image: keeyzar/vsphere-extensions
          imagePullPolicy: Always
          name: rolebinding-creator