apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: default
spec:
  storageClassName: example-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi